// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfwyElgMfB35OaYHgYTQD8ydnq2DKla1U',
    appId: '1:120474864431:web:1a98b10a8a19511215afda',
    messagingSenderId: '120474864431',
    projectId: 'po-pal',
    authDomain: 'po-pal.firebaseapp.com',
    storageBucket: 'po-pal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDmCzEFdgNNCAeZ7goXQIEHWdVApdFce0',
    appId: '1:120474864431:android:fede4313b2eb21bf15afda',
    messagingSenderId: '120474864431',
    projectId: 'po-pal',
    storageBucket: 'po-pal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPBWsib0dbxKRIreZcquxxVRHHoyzro50',
    appId: '1:120474864431:ios:1dbc4cfecfbebc5d15afda',
    messagingSenderId: '120474864431',
    projectId: 'po-pal',
    storageBucket: 'po-pal.firebasestorage.app',
    iosBundleId: 'com.example.poPal',
  );
}